cc_library(
    name = "comp_test",
    srcs = [
        "comp_test.cc",
    ],
    hdrs = [
        "comp_test.hh",
    ],
    include_prefix = "comp_test",
    visibility = ["//visibility:public"],
)
