cc_library(
    name = "static_test",
    hdrs = [
        "static_test.hh",
    ],
    copts = [
        "--std=c++14",
    ],
    include_prefix = "static_test",
    visibility = ["//visibility:public"],
)
