cc_library(
    name = "comp_test",
    srcs = [
    ],
    hdrs = [
        "comp_test.hh",
    ],
    copts = ["-std=c++11"],
    include_prefix = "comp_test",
    visibility = ["//visibility:public"],
)
