name: 'build'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2
      - name: Build & Test
        run: |
          bazel build //...
          bazel test //...

      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Build and run dev container task
      #  uses: devcontainers/ci@v0.2
      #  with:
      #    # Change this to point to your image name
      #    imageName: ghcr.io/dave=hagedorn/cc_comp_test
      #    imageTag: 1
      #    push: true
      #    # Change this to be your CI task/script
      #    runCmd: |
      #      # Add multiple commands to run if needed
      #      bazel test //...
